openapi: 3.1.0
info:
  title: API server for study project "Six Cities".
  description: |-
    * The list of resources and pathes of server "Six Cities".
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: offers
    description: Actions with offers.
  - name: cities
    description: Actions with cities.
  - name: comments
    description: Actions with comments.
  - name: users
    description: Actions with users.
  - name: features
    description: Actions with features.


paths:
  /users/register:
    post:
      tags:
        - users
      summary: User registration
      description: Creates a new user.

      requestBody:
        description: Info for user registration.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true

      responses:
        "201":
          description: User is created. User object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

        "409":
          description: A user with such email already exists.

  /users/login:
    post:
      tags:
        - users
      summary: User authorizatin
      description: Authorizes user based on login and password

    get:
      tags:
        - users
      summary: Checks user status
      description: Gives information for a user
